detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeMethodName:
    accept:
      - f
  UncommunicativeParameterName:
    accept:
      - x
exclude_paths:
  - vendor/
  - _bundler_gems/
  - bin/exec.rb
