AllCops:
  Exclude:
    - 'vendor/**/*'
    - '_bundler_gems/**/*'
    - 'bin/exec.rb'
Layout/MultilineMethodCallIndentation: { EnforcedStyle: indented }
Metrics/BlockLength: { Exclude: ['spec/**/*.rb'] }
Style/Documentation: { Enabled: False }
