#!/usr/bin/env ruby
# frozen_string_literal: true
require 'pp'

def ppp(name)
  lambda do |obj|
    #pp(name => obj)
  end
end

print STDIN
  .each_line
  .tap(&ppp(:each_line))
  .map { |l|
    l
  .tap(&ppp(:line))
      .strip
  .tap(&ppp(:stripped))
      .split(/\s+/)
  .tap(&ppp(:split))
  }
  .select { |k, v| k == "IdentityFile" }
  .tap(&ppp(:selected))
  .map { |k, v| v }
  .tap(&ppp(:value_only))
  .select { |v| v && !v.empty? }
  .tap(&ppp(:non_empty))
  .join("\x00")
