% targets = []
%
% @workspace
% .scroll_repo
% .each_child
% .map(&:basename)
% .map(&:to_s)
% .map(&@workspace.method(:scroll))
% .each do |scroll|
%   builder = @workspace.builders['Vagrant'].new(scroll)
%   return unless builder.handle?(scroll: scroll)
%   artifact = builder.artifact(opts)
%   targets << artifact
%
<%= artifact %>: \
	<%= scroll.packer_yaml_path %> \
	<%= scroll.root / 'source.yaml.erb' %> \
	<%= scroll.root / 'metadata.yaml.erb' %> \

	mkdir -pv <%= artifact.dirname %>
% end

all: \
% targets.each do |target|
	<%= target %> \
% end

clean:
	rm -rf <%= @workspace.artifact_repo %>
